### PR TITLE
chore: clone last 5 commits

### PR DESCRIPTION
**Pull request by DanielRuf**
## Checklist

- [x] All tests are passing
- [ ] New tests were created to address changes in pr (and tests are passing)
- [ ] Updated README and/or documentation, if necessary
- [ ] Added myself / the `contributors` array in package.json

## Changes

Only clone the last 5 commits. By default this was set to 50.

### CODE REVIEW

**Comment by simonepri** [comment]
Hi @DanielRuf, thank you for the PR!
Can you please motivate the choice of the value 5?

**Comment by DanielRuf** [comment]
By default this is `50`, see https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth

**Comment by simonepri** [comment]
Yes I knew, but what's the reason to not use the default?

**Comment by DanielRuf** [comment]
> Yes I knew, but what's the reason to not use the default?

`5` is often faster.

**Comment by DanielRuf** [comment]
Hi @simonepri, can you explain the decision? Would be great =)

**Comment by simonepri** [comment]
Hi DanielRuf,
I cannot see any practical advantage over the default config for this particular small project.

Thank you anyway for the suggestion!

**Pull request closed without merging**
